name: Build, Test and Deploy React App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Docker image and start app
        run: docker-compose up -d --build

      - name: Wait for frontend to be ready
        run: |
          echo "Waiting for the app to be available..."
          sleep 10
          curl --retry 10 --retry-connrefused --retry-delay 5 --fail http://localhost:3000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: echo "Docker already running"
          wait-on: http://localhost:3000

      - name: Stop docker-compose
        run: docker-compose down

      - name: Upload build to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
